### ISSUE TITLE
AppImageAssistant unavailable?

### ISSUE THREAD

**Issue by chrwei** [mastercactapus/easel-driver-linux#1]
it does not appear that AppImageAssistant is part of AppImageKit anymore.  or am I reading their page wrong?

**Comment by probonopd** [comment]
Hi @chrwei correct, it has been replaced by `appimagetool`.

**Comment by chrwei** [comment]
so I just need to change the AIA value in the Makefile?

**Comment by chrwei** [comment]
it's part way there as I can run it with ./AppRun, I just can't get the appimage to compile.

the "build" command complains about the svg not being there, yet it clearly is.

**Comment by probonopd** [comment]
Please make sure that you have `Icon=appname` (without a filename extension) in your desktop file, and `appname.png` in the root of the AppDir. If this doesn't work, please post the relevant log here.

**Comment by chrwei** [comment]
then that's probably it as the .desktop file here in the repo has the extension.

**Comment by chrwei** [comment]
success!  PR #2 submitted.

**Comment by probonopd** [comment]
Thank you.

**Comment by probonopd** [comment]
Can this be closed?

**Comment by chrwei** [comment]
the PR doens't seem to have been merged, so no?

**Comment by probonopd** [comment]
Sorry, you are right of course.

**Comment by mastercactapus** [comment]
Closing this now that the PR has been merged. Thanks @chrwei !
